<?php


namespace AcikVeri\Importer\Providers;


use Illuminate\Support\ServiceProvider;

class ImporterServiceProvider extends ServiceProvider
{
    public function boot()
    {

    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
